### PR TITLE
fix js syntax error

### PR DESCRIPTION
**Pull request by mrzzcn**
got error under node(v7.9.0)

### CODE REVIEW

**Comment by notwaldorf** [comment]
Whaaaaa but it's a promise? Did the promise syntax change?

**Comment by Garbee** [comment]
I'm running the same version and have no problems. @mrzzcn Can you please provide steps to reproduce the issue?

**Comment by mrzzcn** [comment]
sorry, missed this. steps

**Comment by mrzzcn** [comment]
so unprofessional !!!

**Comment by notwaldorf** [comment]
The `steps` image isn't loading, and I can't repro an error, so closing :(
Please re-open if there's actual repro steps I can look at, or an explanation as to what you think may be causing this

**Pull request closed without merging**
