### PR TITLE
v1.4.0

### PR DESCRIPTION
**Pull request by mojoaxel**
Release Notes:
### MAJOR
* _none_

### MINOR
* Removed support for `git-standup`. The `TTC_GITBOT` setting is ignored from now on!
* Added `TTC_POMODORO` and `TTC_BREAK` settings
* Added more details to the displayed repo name
* Show "Loading commits.." message while loading.

### PATCH
* Changed commit history from "Last day" to "Last 24 hours"
* Improved error handling
* Updated the twitter api
* Fix text overflow issue in ascii-art boxes
* Fix text length issue when there is an emoji in it

### CODE REVIEW

**Comment by mojoaxel** [comment]
@notwaldorf Could you please merge and release this. Thx!

**Comment by notwaldorf** [comment]
Trying a release right now!

**Comment by notwaldorf** [comment]
Hmm good news and bad news:
Good news: we're on `1.4.0` now. 🎉 
Bad news: it totally crashes for me and doesn't work (i had tested that the previous 1.3.1 version did work before installing it):
screen shot 2018-05-22 at 2 15 47 pm

**Comment by notwaldorf** [comment]
Ah interesting, it's because my TTC_REPOS is `TTC_REPOS="~/Code"`, and it seems to expect `TTC_REPOS="/Users/noms/Code"`.

**Comment by notwaldorf** [comment]
I'll add a note to the readme and ship 1.4.1 in the meantime.

**Comment by mojoaxel** [comment]
Thx and sorry!
No idea what is going on. I'll have a look as soon as I find the time.

**Pull request merged**
