### PR TITLE
fix usage of git-user-name

### PR DESCRIPTION
**Pull request by mojoaxel**
see https://github.com/notwaldorf/tiny-care-terminal/commit/d8ae36a7096d381a8437602e99c32ff9148808f1#r37227215

### CODE REVIEW

**Comment by fluxsauce** [comment]
I was about to submit a similar PR, my version was a minor adaptation of what's already there:

```js
let gitUsername;

try {
  gitUsername = require('git-user-name')();
} catch(err) {
  console.error(`ERROR reading git-config.
    Use e.g. 'git config --global user.name "Mona Lisa"'.
    See 'man git config' for further information.
  `);
  return process.exit(0);
}
```

but I like the require at the top of the file better. FWIW, LGTM

**Comment by micgro42** [comment]
Thank you for looking into this so quickly!

It doesn't crash anymore, but it fails to correctly detect the git username for me. The challenge seems to be that my git username and email is part of a file that is included in my global git config.

FWIW, `getGitUsername()` did not throw an exception, it just returned undefined.

A first look suggests that [`git-user-name`](https://github.com/jonschlinkert/git-user-name/blob/22cf1d3880356c754f7d84dec242987a3b8fcc7e/index.js) only parses the global git config file, but doesn't evaluate the includes therein.

Using includes is a common strategy if one wants to source-control one's general git configuration while also keeping a local configuration. This allows one to have different git emails for work and private.

Getting the git username could be done directly using the shell with something like the following + error handling:
```js
const { exec } = require("child_process");

async function getGitUser() {
    return new Promise((resolve, reject) => {
        exec('git config --global --includes --get user.name', (error, stdout, stderr) => {

            // handle errors here

            resolve(stdout);
        });
    });
}
```

However, `gitlog()` _still_ returned all commits and also with wrong commit hashes? o.O I'll try to find out more as soon as I can find the time. Maybe my setup is just weird. Don't wait for me with merging this, the crash seems to be fixed.

**Comment by micgro42** [comment]
Ah, `stdout` has a trailing newline, that was the problem. This works:
```js
const { exec } = require("child_process");

async function getGitUser() {
  return new Promise((resolvePromise, rejectPromise) => {
    exec('git config --get user.name', (error, stdout, stderr) => {

      // do error handling here

      resolvePromise(stdout.trim());
    });
  });
}
```

**Comment by mojoaxel** [comment]
> It lets you even drop the dependency on git-user-name.

Let's first get this PR merges and than @micgro42 can provide an new PR with further improments! :+1: :rocket:

**Pull request merged**
